### ISSUE TITLE
Apt key can't be added "gpg: no valid OpenPGP data found."

### ISSUE THREAD

**Issue by darkwizard242** [AdoptOpenJDK/openjdk-installer#281] opened 2021-01-12 21:53 UTC
Hi Folks,

Guessing that an issue might be on-going on the infrastructure side, the GPG key can't be retrieved at the moment.

For instance:

```shell
$ wget  -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -

gpg: no valid OpenPGP data found.
```

With a get request:
```shell
$ http -Fh get https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

HTTP/1.1 503 Service Temporarily Unavailable
Connection: keep-alive
Content-Length: 190
Content-Type: text/html
Date: Tue, 12 Jan 2021 21:52:13 GMT
```

**Comment by aahlenst** [comment] 2021-01-13 07:50
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1830.

**Closed by aahlenst** 2021-01-13 07:50 UTC
