### ISSUE TITLE
Windows MSI installer failed with exit code 1603

### ISSUE THREAD

**Issue by Eskibear** [AdoptOpenJDK/openjdk-installer#196] opened 2020-02-26 12:59 UTC
Originally reported in https://github.com/microsoft/vscode-java-pack/issues/310 by @ManoSinistra15 

Our product basically just downloads latest AdoptOpenJDK's MSI installer, and executes it. And below is the error message reported by the enduser. 

[1:20:18 PM] Error: Command failed with exit code 1603: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\username\AppData\Local\Temp\1WBni7p1RXz2l2Ly16XoZJ5Ip8B\resources\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.6_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\username\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive

**Comment by aahlenst** [comment] 2020-02-26 16:00
AFAIK 1603 is a generic fatal MSI error. Some log would help. https://docs.microsoft.com/de-ch/archive/blogs/astebner/help-me-help-you-if-you-have-setup-bugs works with AdoptOpenJDK MSIs and produces a nice log.

I checked the command given above and it installs fine.

**Comment by Eskibear** [comment] 2020-02-26 16:11
sure. I myself can not reproduce the error either. But I believe there must be cases uncovered, as we've reveiced several similar issues.  I'm not familiar with MSI as you guys are, is there any parameters I can append to the command to save users' log, so they are able to upload when error occurs?

**Comment by aahlenst** [comment] 2020-02-27 11:21
`/l*v %temp%\AdoptOpenJDK-MSI.log` creates a verbose log in `%temp%\AdoptOpenJDK-MSI.log`. Does that suffice? The full command would be:

```
C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Administrator\Downloads\OpenJDK11U-jdk_x64_windows_hotspot_11.0.6_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\Administrator\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v %temp%\AdoptOpenJDK-MSI.log
```

**Comment by Eskibear** [comment] 2020-02-27 13:35
Thanks, I'll append that in our product, and ask uesrs to provide the log when error occurs.

**Comment by aahlenst** [comment] 2020-02-28 07:47
I close the issue for the time being because it seems we cannot do anything else at the moment. Feel free to raise another issue or reopen this one.

**Comment by Eskibear** [comment] 2020-07-27 16:35
I'm re-opening it.
Here is the [AdoptOpenJDK-MSI.log](https://github.com/microsoft/vscode-java-installer/files/4981630/AdoptOpenJDK-MSI.log) from @EngineerFaunce 
Please take a look.

**Comment by aahlenst** [comment] 2020-07-28 10:57
Thanks for the puzzle. I learnt about a new quirk of msiexec 😄 

This happens if AdoptOpenJDK has been installed on the machine before and another installation is attempted of the exact same version (GUID, Product ID) **but the name of the MSI is different**. It does not matter whether it's a per-user or per-machine installation

The key here are those lines in the log:
```
MSI (s) (E8:68) [21:06:55:587]: Note: 1: 2203 2: C:\Users\exoti\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\target.msi 3: -2147287038 
MSI (s) (E8:68) [21:06:55:587]: Note: 1: 1316 2: C:\Users\exoti\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\target.msi 
MSI (s) (E8:68) [21:06:55:587]: SECREPAIR: Error determining package source type
MSI (s) (E8:68) [21:06:55:587]: SECUREREPAIR: SecureRepair Failed. Error code: 524237E0930
MSI (s) (E8:68) [21:06:55:587]: Note: 1: 2205 2:  3: Error 
MSI (s) (E8:68) [21:06:55:587]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (E8:68) [21:06:55:587]: Product: AdoptOpenJDK JDK with Hotspot 11.0.8.10 (x64) -- Error 1316. The specified account already exists.


Error 1316. The specified account already exists.

```

This basically says that AdoptOpenJDK 11.0.8 was previously installed as `target.msi`. msiexec is now looking again for `target.msi`, but at the beginning of the log one can see that the name of the installer file is `OpenJDK11U-jdk_x64_windows_hotspot_11.0.8_10.msi`. This file does not exist and things go downhill from there.

This does not happen if another version of AdoptOpenJDK has been installed before, for example 11.0.7. Instead, two versions are installed: 11.0.7 and 11.0.8.

Googling did not yield a satisfying workaround on the MSI side. What I would do (sorted by descending preference):

* Use a ZIP instead of an MSI if the JDK is for VS Code only. The existence of the JDK is not surfaced to the user and the user never ends up different versions, multiple JDKs and potential PATH pollution. This is more or less what JetBrains does, except that they have their own JDK.
* Query the registry if AdoptOpenJDK is already installed and what version. The info is stored in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\` (64 bit) or `HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall` (32 bit). The product ID is `{FDC10A03-67E2-4282-B16A-A8B113A80456}` for 11.0.8. The product ID changes with every version. If the same version has already been installed, do nothing.

@douph1 Do you have a better idea?

**Comment by douph1** [comment] 2020-09-08 08:08
I think it is exactly the same as #246 
>MSI (s) (E8:68) [21:06:52:322]: Determined that existing product (either this product or the product being upgraded with a >patch) is installed per-machine.^M
>MSI (s) (E8:68) [21:06:52:322]: PROPERTY CHANGE: Adding MSIINSTALLPERUSER property. Its value is '1'.^M
>MSI (s) (E8:68) [21:06:52:322]: PROPERTY CHANGE: Modifying ALLUSERS property. Its current value is '2'. Its new value: '1'.^M

https://docs.microsoft.com/en-us/windows/win32/msi/msiinstallperuser
>f Windows Installer installs the application in the per-machine context, it resets the value of the ALLUSERS property to 1


Some similar problem and solution:
https://support.arcserve.com/s/article/202151279?language=en_US
...
 this may be caused by an issue with a previously existing copy of the package to be installed (for instance when doing an upgrade) which has not been cleaned up properly.
...
In this case it is necessary to make sure that any previously installed products are removed from the system and their corresponding MSI are cleared.


So definitely I think it is a previous per-machine install

**Comment by karianna** [comment] 2020-09-15 08:11
@Eskibear - Can you confirm you're able to work around this given the explanation?

**Comment by Eskibear** [comment] 2020-09-15 15:36
@karianna Sure, we definitly have chance to improve detection of previously installed products, before we actually execute the MSI. In the worst case, we can still fallback to use ZIP instead of MSI.

Thank you guys for the investigation and explanation.

**Closed** 2020-09-17 08:55 UTC
Labels: duplicate
