### ISSUE TITLE
Installation failure on Ubuntu 16.04 LTS | adoptopenjdk-11-hotspot

### ISSUE THREAD

**Issue by darkwizard242** [AdoptOpenJDK/openjdk-installer#227] opened 2020-06-17 14:23 UTC
### Description:

Failing to update repository cache due to errors caused after adding adoptopenjdk repository.

Contents of `/etc/apt/sources.list.d/adoptopenjdk.list`:

```shell
deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ xenial main
``` 

**Error within an Ubuntu 16.04 Container:**
```shell
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Ign:3 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial InRelease            
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]           
Ign:5 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release                           
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages               
Get:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main all Packages
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main all Packages
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main all Packages
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main all Packages
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main all Packages
Err:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages
  Unknown date format
```

**Error within an Ubuntu 16.04 AWS EC2 instance:**
```shell
Err:13 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages
404  Not Found
Ign:14 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main all Packages
Ign:15 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main Translation-en_US
Ign:16 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main Translation-en
Reading package lists...
W: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release' does not have a Release file.
E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by aahlenst** [comment] 2020-06-17 14:24
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1399.

**Closed by aahlenst** 2020-06-17 14:24 UTC
