### ISSUE TITLE
JDK8 & JDK11  and JDk14 build failing due to Installer issue : Execution error: null

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-installer#224] opened 2020-06-15 09:21 UTC
jdk8 & jdk11 jdk14 nightly builds failing with the same error

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-hotspot/568/console

Installer issue 
`Execution error: null`

**Comment by M-Davies** [comment] 2020-06-15 09:23
```
> Task :deb:uploadDebianPackage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':deb:uploadDebianPackage' (type 'UploadDebianPackage').
> No value has been specified for property 'repository'.
```

**Comment by M-Davies** [comment] 2020-06-15 09:29
Likely caused by https://github.com/AdoptOpenJDK/openjdk-installer/pull/221 (FYI @jennli)
Specifically this code at a straight up guess:
```java
repository: [
            deb: ARTIFACTORY_REPOSITORY_DEB,
            rpm: ARTIFACTORY_REPOSITORY_RPM
            deb: hasProperty("ARTIFACTORY_REPOSITORY_DEB") ? ARTIFACTORY_REPOSITORY_DEB : null,
            rpm: hasProperty("ARTIFACTORY_REPOSITORY_RPM") ? ARTIFACTORY_REPOSITORY_RPM : null,
        ],
```

**Comment by karianna** [comment] 2020-06-15 10:22
Assigning to @aahlenst in the meantime until @jennli invite to the team I just sent gets accepted :-)

**Closed** 2020-06-15 13:28 UTC
Labels: bug

**Comment by jennli** [comment] 2020-06-15 17:33
sorry about that and thanks @aahlenst for the quick fix
