### ISSUE TITLE
Could not find JDK to sign on windows

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-installer#240] opened 2020-07-30 14:57 UTC
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/689/console 
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-hotspot/626/console

The above builds installers struggled to find the jdk (not jre). 
```
First .\SourceDir\OpenJDK11\hotspot\x86-32\jdk-11.0.9 not exists
Second .\SourceDir\OpenJDK11\hotspot\x86-32\jdk-11+9 not exists
Third .\SourceDir\OpenJDK11\hotspot\x86-32\jdk-11.0.9+9 not exists
OpenJDK-Latest unnumbered .\SourceDir\OpenJDK-Latest\hotspot\x86-32\jdk-11.0.9+9 does not exist
SOURCE Dir not found / failed
```

**Comment by karianna** [comment] 2020-07-30 17:12
@douph1 one for you I think

**Comment by M-Davies** [comment] 2020-08-03 08:48
Recurrence on https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/694/console

**Comment by douph1** [comment] 2020-08-10 21:15
Last time I see it with this version numbering there was a version mismatch between the job parameters and what is in the zip file.
11.0.9+9 vs 11.0.8+9 something like that.

**Comment by douph1** [comment] 2020-08-10 21:16
So the error is on the caller side. Please see and copy paste more of the console log to see the directory path where the zip file is extracted

**Comment by andrew-m-leonard** [comment] 2020-08-11 08:06
Looking at the upstream build artifact: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/702/console
```
01:10:15  OpenJDK JDK path will be jdk-11.0.8+9. JRE path will be jdk-11.0.8+9-jre
01:10:15  Archiving the build OpenJDK image and compressing with gzip
01:10:24  Your final archive was created at /cygdrive/c/workspace/openjdk-build/workspace/build/src/build/windows-x86_64-normal-clientANDserver-release/images/OpenJDK.zip
01:10:24  Moving the artifact to /cygdrive/c/workspace/openjdk-build/workspace/target/
01:10:24  OpenJDK test image path will be jdk-11.0.8+9-test-image.
01:10:24  Archiving the build OpenJDK image and compressing with gzip
01:10:28  Your final archive was created at /cygdrive/c/workspace/openjdk-build/workspace/build/src/build/windows-x86_64-normal-clientANDserver-release/images/OpenJDK.zip
01:10:28  Moving the artifact to /cygdrive/c/workspace/openjdk-build/workspace/target/
01:10:28  Archiving the build OpenJDK image and compressing with gzip
01:10:47  Your final archive was created at /cygdrive/c/workspace/openjdk-build/workspace/build/src/build/windows-x86_64-normal-clientANDserver-release/images/OpenJDK.zip
01:10:47  Moving the artifact to /cygdrive/c/workspace/openjdk-build/workspace/target/
01:10:47  All done!
[Pipeline] readFile
[Pipeline] echo
01:10:47  openjdk version "11.0.9" 2020-10-20
01:10:47  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+9-202008102349)
01:10:47  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+9-202008102349, mixed mode)
01:10:47 
```
It seems the jdk level is 11.0.9+9, but the build script is creating a jdk file path of jdk-11.0.8+9-jre

**Comment by andrew-m-leonard** [comment] 2020-08-11 08:13
In fact the jdk level should be jdk-11.0.9+2, not sure where it's got jdk-11.0.9+9 from?!

**Comment by andrew-m-leonard** [comment] 2020-08-11 08:17
build configure args specifies --with-version-build=9 for some reason?:
```
00:49:12  Running ./configure with arguments 'bash ./configure --verbose  --with-milestone=fcs --with-version-opt=202008102349 --without-version-pre --with-version-build=9 --with-vendor-version-string=AdoptOpenJDK --with-vendor-url=https://adoptopenjdk.net/ --with-vendor-name=AdoptOpenJDK --with-vendor-bug-url=https://github.com/AdoptOpenJDK/openjdk-support/issues --with-vendor-vm-bug-url=https://github.com/AdoptOpenJDK/openjdk-support/issues --with-boot-jdk=/cygdrive/c/openjdk/jdk-10 --with-debug-level=release --with-native-debug-symbols=none --with-jvm-variants=client,server  --disable-warnings-as-errors --disable-ccache --with-toolchain-version=2017 '
```

**Comment by andrew-m-leonard** [comment] 2020-08-11 08:28
The problem is the chronological order of the jdk tags in OpenJDK and the way the build logic determines the latest tag: https://github.com/AdoptOpenJDK/openjdk-build/blob/9148896926f269c42d36d40a9edd9248b0d601cb/sbin/build.sh#L722
Chronologically the latest tag is jdk-11.0.8+9, but the latest numerically is jdk-11.0.9+2, however since jdk-11.0.9+2 was authored back in March and then merged, it is chronologically quite old... OpenJ9 builds use a different method to determine the tag, using a chrono sort by name and then persisting in a file as part of the merge process.

**Comment by andrew-m-leonard** [comment] 2020-08-11 08:28
The problem should resolve once OpenJDK commit a brand new build level for jdk-11.0.9+3

**Comment by douph1** [comment] 2021-01-25 07:34
No problem since next release

**Closed by douph1** 2021-01-25 07:34 UTC
Labels: bug
